name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Instalar Dependencias
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # Instalando versões estáveis para evitar erros rápidos
          pip3 install --user --upgrade "buildozer>=1.5.0" "Cython<3.0" virtualenv

      - name: Criar APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Aceita as licenças e roda o build direto
          buildozer -v android debug --accept-sdk-license
          
      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: APK_SISTEMA
          path: bin/*.apk
          
