name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Dependencias
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Fabricar APK com Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes y | buildozer -v android debug

      - name: Enviar APK Pronto
        uses: actions/upload-artifact@v3
        with:
          name: meu-projeto-apk
          path: bin/*.apk
          
