name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Dependencias
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Configurar e Aceitar Licencas
        run: |
          export PATH=$PATH:$HOME/.local/bin
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          # Este comando aceita as licen√ßas sem precisar do 'yes'
          buildozer android p4a -- accept-sdk-license || true

      - name: Fabricar APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Rodando sem o 'yes' para testar a estabilidade
          buildozer -v android debug
          
      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: sistema-final
          path: bin/*.apk
          
