name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Instalar Dependencias
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Fabricar APK (Sem Cache)
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Força o Buildozer a aceitar a licença e rodar de forma limpa
          buildozer -v android debug --accept-sdk-license
          
      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: sistema-final
          path: bin/*.apk
          
